//! `nub init` — generate a starter config file. Never updated by nub
//! after the initial write; the operator owns it.

use anyhow::{anyhow, Context, Result};
use std::fs;
use std::io::Write;
use std::path::PathBuf;

const TEMPLATE: &str = r#"# nub config — generated by `nub init`. Edit freely; nub re-reads on restart.
# Docs: https://github.com/TerryTsai/nub#configuration

id   = "{ID}"
bind = "0.0.0.0:8080"

# tls_cert = "/etc/nub/cert.pem"            # PEM cert path; pair with tls_key
# tls_key  = "/etc/nub/key.pem"

# allowed_binds = ["/data/nub"]             # host paths usable as bind-mount sources
# dockerfiles   = "/srv/nub/dockerfiles"    # default: $XDG_DATA_HOME/nub/dockerfiles

# [[trust]]
# id      = "phone"
# token   = "long-random-string-share-with-the-phone"
# allowed = ["host_info", "list_containers", "stream_logs", "stream_stats"]

# [[trust]]
# id      = "admin-laptop"
# token   = "..."
# allowed = ["*"]
"#;

pub fn run(path: Option<String>, force: bool) -> Result<()> {
    let body = TEMPLATE.replace("{ID}", &super::hostname());

    if path.as_deref() == Some("-") {
        std::io::stdout().write_all(body.as_bytes())?;
        return Ok(());
    }

    let target = path.map(PathBuf::from).unwrap_or_else(default_path);
    if target.exists() && !force {
        return Err(anyhow!(
            "{} already exists; pass --force to overwrite",
            target.display()
        ));
    }
    if let Some(parent) = target.parent() {
        fs::create_dir_all(parent).with_context(|| format!("creating {}", parent.display()))?;
    }
    fs::write(&target, body).with_context(|| format!("writing {}", target.display()))?;
    println!("wrote {}", target.display());
    Ok(())
}

/// Default config path: `$XDG_CONFIG_HOME/nub/nub.toml`.
pub fn default_path() -> PathBuf {
    crate::config::xdg_config_home().join("nub/nub.toml")
}
