//! `nub systemd-unit` — print a systemd unit file for nub on stdout.
//! `ExecStart` is set to the binary's `current_exe()` so the unit always
//! points back at the same nub that emitted it. Re-run after a binary
//! upgrade to refresh.

use anyhow::Result;
use std::io::Write;

pub fn print_unit(user_level: bool) -> Result<()> {
    let exec = std::env::current_exe()
        .ok()
        .and_then(|p| p.to_str().map(String::from))
        .unwrap_or_else(|| "/usr/local/bin/nub".to_string());
    let unit = if user_level {
        user_unit(&exec)
    } else {
        system_unit(&exec)
    };
    std::io::stdout().write_all(unit.as_bytes())?;
    Ok(())
}

fn user_unit(exec: &str) -> String {
    format!(
        r#"# nub user-level systemd unit. Generated by `nub systemd-unit --user`.
# Drop into ~/.config/systemd/user/nub.service. Re-run after a binary
# upgrade to refresh ExecStart if it ever moves.
#
# Enable + start:
#   systemctl --user daemon-reload
#   systemctl --user enable --now nub
#
# For nub to keep running when you're not logged in, enable lingering:
#   sudo loginctl enable-linger $USER

[Unit]
Description=nub Docker/Podman control plane
After=default.target

[Service]
Type=simple
ExecStart={exec}
Restart=on-failure
RestartSec=2s

[Install]
WantedBy=default.target
"#
    )
}

fn system_unit(exec: &str) -> String {
    format!(
        r#"# nub system-level systemd unit. Generated by `nub systemd-unit --system`.
# Drop into /etc/systemd/system/nub.service.
#
# This template runs nub as root. To run as a different user, add a
# `User=` directive under [Service] and ensure that user has access to
# the engine socket (typically the `docker` group, or owns the rootless
# Podman socket).
#
# Enable + start:
#   sudo systemctl daemon-reload
#   sudo systemctl enable --now nub

[Unit]
Description=nub Docker/Podman control plane
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart={exec}
Restart=on-failure
RestartSec=2s

[Install]
WantedBy=multi-user.target
"#
    )
}
