//! `nub init` — generate a starter config file. Never updated by nub after.

use anyhow::{anyhow, Context, Result};
use std::fs;
use std::io::{BufRead, Write};
use std::path::{Path, PathBuf};

const TEMPLATE: &str = r#"# nub config — generated by `nub init`. Edit freely; nub re-reads on restart.
# Docs: https://github.com/TerryTsai/nub#configuration

id   = "{ID}"
bind = "0.0.0.0:8080"

# tls_cert = "/etc/nub/cert.pem"            # recognized but TLS not yet wired
# tls_key  = "/etc/nub/key.pem"

# allowed_binds = ["/data/nub"]             # host paths usable as bind-mount sources
# dockerfiles   = "/srv/nub/dockerfiles"    # default: $XDG_DATA_HOME/nub/dockerfiles

# [[trust]]
# id      = "phone"
# token   = "long-random-string-share-with-the-phone"
# allowed = ["host_info", "list_containers", "stream_logs", "stream_stats"]

# [[trust]]
# id      = "admin-laptop"
# token   = "..."
# allowed = ["*"]
"#;

pub fn run(path: Option<String>, force: bool) -> Result<()> {
    let body = TEMPLATE.replace("{ID}", &hostname());

    if path.as_deref() == Some("-") {
        std::io::stdout().write_all(body.as_bytes())?;
        return Ok(());
    }

    let target = path.map(PathBuf::from).unwrap_or_else(default_path);
    if target.exists() && !force {
        return Err(anyhow!(
            "{} already exists; pass --force to overwrite",
            target.display()
        ));
    }
    if let Some(parent) = target.parent() {
        fs::create_dir_all(parent).with_context(|| format!("creating {}", parent.display()))?;
    }
    fs::write(&target, body).with_context(|| format!("writing {}", target.display()))?;
    println!("wrote {}", target.display());
    Ok(())
}

/// Best-effort hostname. Falls back to "nub" if /etc/hostname is unreadable.
pub fn hostname() -> String {
    fs::read_to_string("/etc/hostname")
        .or_else(|_| fs::read_to_string("/proc/sys/kernel/hostname"))
        .ok()
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| "nub".into())
}

/// Default config path: `$XDG_CONFIG_HOME/nub/nub.toml`.
pub fn default_path() -> PathBuf {
    crate::config::xdg_config_home().join("nub/nub.toml")
}

/// Wipe `$XDG_CONFIG_HOME/nub` and `$XDG_DATA_HOME/nub`. Prompts for
/// confirmation unless `yes` is set. The binary itself isn't touched —
/// users who installed via `install.sh` can `rm /usr/local/bin/nub`.
pub fn uninstall(yes: bool) -> Result<()> {
    let cfg = crate::config::xdg_config_home().join("nub");
    let data = crate::config::xdg_data_home().join("nub");
    let targets: [&Path; 2] = [cfg.as_path(), data.as_path()];

    let existing: Vec<&Path> = targets.iter().copied().filter(|p| p.exists()).collect();
    if existing.is_empty() {
        println!(
            "nothing to remove (neither {} nor {} exist)",
            cfg.display(),
            data.display()
        );
        return Ok(());
    }

    println!("the following will be deleted:");
    for p in &existing {
        println!("  {}", p.display());
    }
    if !yes {
        print!("proceed? [y/N] ");
        std::io::stdout().flush().ok();
        let mut answer = String::new();
        std::io::stdin().lock().read_line(&mut answer)?;
        if !answer.trim().eq_ignore_ascii_case("y") {
            println!("cancelled");
            return Ok(());
        }
    }
    for p in &existing {
        fs::remove_dir_all(p).with_context(|| format!("removing {}", p.display()))?;
        println!("removed {}", p.display());
    }
    Ok(())
}
