//! `nub init` — generate a starter config file. Never updated by nub after.

use anyhow::{anyhow, Context, Result};
use std::fs;
use std::io::{BufRead, Write};
use std::path::{Path, PathBuf};

const TEMPLATE: &str = r#"# nub config — generated by `nub init`. Edit freely; nub re-reads on restart.
# Docs: https://github.com/TerryTsai/nub#configuration

id   = "{ID}"
bind = "0.0.0.0:8080"

# tls_cert = "/etc/nub/cert.pem"            # PEM cert path; pair with tls_key
# tls_key  = "/etc/nub/key.pem"

# allowed_binds = ["/data/nub"]             # host paths usable as bind-mount sources
# dockerfiles   = "/srv/nub/dockerfiles"    # default: $XDG_DATA_HOME/nub/dockerfiles

# [[trust]]
# id      = "phone"
# token   = "long-random-string-share-with-the-phone"
# allowed = ["host_info", "list_containers", "stream_logs", "stream_stats"]

# [[trust]]
# id      = "admin-laptop"
# token   = "..."
# allowed = ["*"]
"#;

pub fn run(path: Option<String>, force: bool) -> Result<()> {
    let body = TEMPLATE.replace("{ID}", &hostname());

    if path.as_deref() == Some("-") {
        std::io::stdout().write_all(body.as_bytes())?;
        return Ok(());
    }

    let target = path.map(PathBuf::from).unwrap_or_else(default_path);
    if target.exists() && !force {
        return Err(anyhow!(
            "{} already exists; pass --force to overwrite",
            target.display()
        ));
    }
    if let Some(parent) = target.parent() {
        fs::create_dir_all(parent).with_context(|| format!("creating {}", parent.display()))?;
    }
    fs::write(&target, body).with_context(|| format!("writing {}", target.display()))?;
    println!("wrote {}", target.display());
    Ok(())
}

/// Best-effort hostname. Falls back to "nub" if /etc/hostname is unreadable.
pub fn hostname() -> String {
    fs::read_to_string("/etc/hostname")
        .or_else(|_| fs::read_to_string("/proc/sys/kernel/hostname"))
        .ok()
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| "nub".into())
}

/// Default config path: `$XDG_CONFIG_HOME/nub/nub.toml`.
pub fn default_path() -> PathBuf {
    crate::config::xdg_config_home().join("nub/nub.toml")
}

/// Print a systemd unit file for nub on stdout. `user_level` chooses
/// between a user-level (`~/.config/systemd/user/nub.service`) and a
/// system-level (`/etc/systemd/system/nub.service`) template.
///
/// `ExecStart` is set to the binary's current path (via
/// `std::env::current_exe`) so the unit always points back at the same
/// nub that emitted it. Re-run after a binary upgrade to refresh.
pub fn systemd_unit(user_level: bool) -> Result<()> {
    let exec = std::env::current_exe()
        .ok()
        .and_then(|p| p.to_str().map(String::from))
        .unwrap_or_else(|| "/usr/local/bin/nub".to_string());
    let unit = if user_level {
        user_unit(&exec)
    } else {
        system_unit(&exec)
    };
    std::io::stdout().write_all(unit.as_bytes())?;
    Ok(())
}

fn user_unit(exec: &str) -> String {
    format!(
        r#"# nub user-level systemd unit. Generated by `nub systemd-unit --user`.
# Drop into ~/.config/systemd/user/nub.service. Re-run after a binary
# upgrade to refresh ExecStart if it ever moves.
#
# Enable + start:
#   systemctl --user daemon-reload
#   systemctl --user enable --now nub
#
# For nub to keep running when you're not logged in, enable lingering:
#   sudo loginctl enable-linger $USER

[Unit]
Description=nub Docker/Podman control plane
After=default.target

[Service]
Type=simple
ExecStart={exec}
Restart=on-failure
RestartSec=2s

[Install]
WantedBy=default.target
"#
    )
}

fn system_unit(exec: &str) -> String {
    format!(
        r#"# nub system-level systemd unit. Generated by `nub systemd-unit --system`.
# Drop into /etc/systemd/system/nub.service.
#
# This template runs nub as root. To run as a different user, add a
# `User=` directive under [Service] and ensure that user has access to
# the engine socket (typically the `docker` group, or owns the rootless
# Podman socket).
#
# Enable + start:
#   sudo systemctl daemon-reload
#   sudo systemctl enable --now nub

[Unit]
Description=nub Docker/Podman control plane
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart={exec}
Restart=on-failure
RestartSec=2s

[Install]
WantedBy=multi-user.target
"#
    )
}

/// Wipe `$XDG_CONFIG_HOME/nub` and `$XDG_DATA_HOME/nub`. Prompts for
/// confirmation unless `yes` is set. The binary itself isn't touched —
/// users who installed via `install.sh` can `rm /usr/local/bin/nub`.
pub fn uninstall(yes: bool) -> Result<()> {
    let cfg = crate::config::xdg_config_home().join("nub");
    let data = crate::config::xdg_data_home().join("nub");
    let targets: [&Path; 2] = [cfg.as_path(), data.as_path()];

    let existing: Vec<&Path> = targets.iter().copied().filter(|p| p.exists()).collect();
    if existing.is_empty() {
        println!(
            "nothing to remove (neither {} nor {} exist)",
            cfg.display(),
            data.display()
        );
        return Ok(());
    }

    println!("the following will be deleted:");
    for p in &existing {
        println!("  {}", p.display());
    }
    if !yes {
        print!("proceed? [y/N] ");
        std::io::stdout().flush().ok();
        let mut answer = String::new();
        std::io::stdin().lock().read_line(&mut answer)?;
        if !answer.trim().eq_ignore_ascii_case("y") {
            println!("cancelled");
            return Ok(());
        }
    }
    for p in &existing {
        fs::remove_dir_all(p).with_context(|| format!("removing {}", p.display()))?;
        println!("removed {}", p.display());
    }
    Ok(())
}
