//! `nub init` — generate a starter config file. Never updated by nub after.

use anyhow::{anyhow, Context, Result};
use std::fs;
use std::io::Write;
use std::path::PathBuf;

const TEMPLATE: &str = r#"# nub config — generated by `nub init`. Edit freely; nub re-reads on restart.
# Docs: https://github.com/TerryTsai/nub#configuration

id   = "{ID}"
bind = "0.0.0.0:8080"

# tls_cert = "/etc/nub/cert.pem"   # recognized but TLS not yet wired
# tls_key  = "/etc/nub/key.pem"

# [engine]
# allowed_binds = ["/data/nub"]    # only when relaxing bind-mount restrictions

# [[trust]]
# id      = "phone"
# token   = "long-random-string-share-with-the-phone"
# allowed = ["host_info", "list_containers", "stream_logs", "stream_stats"]

# [[trust]]
# id      = "admin-laptop"
# token   = "..."
# allowed = ["*"]
"#;

pub fn run(path: Option<String>, force: bool) -> Result<()> {
    let body = TEMPLATE.replace("{ID}", &hostname());

    if path.as_deref() == Some("-") {
        std::io::stdout().write_all(body.as_bytes())?;
        return Ok(());
    }

    let target = path.map(PathBuf::from).unwrap_or_else(default_path);
    if target.exists() && !force {
        return Err(anyhow!(
            "{} already exists; pass --force to overwrite",
            target.display()
        ));
    }
    if let Some(parent) = target.parent() {
        fs::create_dir_all(parent).with_context(|| format!("creating {}", parent.display()))?;
    }
    fs::write(&target, body).with_context(|| format!("writing {}", target.display()))?;
    println!("wrote {}", target.display());
    Ok(())
}

/// Best-effort hostname. Falls back to "nub" if /etc/hostname is unreadable.
pub fn hostname() -> String {
    fs::read_to_string("/etc/hostname")
        .or_else(|_| fs::read_to_string("/proc/sys/kernel/hostname"))
        .ok()
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| "nub".into())
}

/// Default config path: $XDG_CONFIG_HOME/nub/nub.toml (or ~/.config/nub/nub.toml).
pub fn default_path() -> PathBuf {
    if let Some(x) = std::env::var_os("XDG_CONFIG_HOME") {
        return PathBuf::from(x).join("nub/nub.toml");
    }
    if let Some(h) = std::env::var_os("HOME") {
        return PathBuf::from(h).join(".config/nub/nub.toml");
    }
    PathBuf::from("./nub.toml")
}
